
name: CI

on: [push, pull_request]

jobs:

  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        name: Checkout repo

      - run: npm install
        name: Install dependencies

      - run: npm run lint
        name: Lint

      - run: npm run test
        name: Unit test

      - run: npm run clean && tsc && npm run ncc
        name: Build

      - uses: ./
        name: Integration test
